### Register a new bike
@rental = http://localhost:8080
POST {{rental}}/bikes?bikeType=city&location=Utrecht

### List all
# Show available bikes
GET {{rental}}/bikes
Accept: application/json

### Bike status
# Show bike status
GET {{rental}}/bikes/7ccaf4bc-f526-41fa-b496-1fa1214bedd6
Accept: application/json

### Request Bike
# Request one of the available bikes
POST {{rental}}/requestBike?bikeId=7ccaf4bc-f526-41fa-b496-1fa1214bedd6
Accept: application/json