@payment = http://localhost:8081
@paymentReference = eaeb5a1f-13df-4611-9e32-228af47e7d04
@paymentId = d82df2c3-1120-4994-84ea-f6eddcc85f45

### Prepare Payment
POST {{payment}}/preparePayment?amount=1000&rentalReference={{paymentReference}}
Accept: application/json

### Get Payment Status
GET {{payment}}/status/{{paymentId}}
Accept: application/json

### Find paymentID
# Find the payment for a specific payment reference
GET {{payment}}/findPayment?reference={{paymentReference}}
Accept: application/json

