@payment = http://localhost:8081
@paymentReference = eaeb5a1f-13df-4611-9e32-228af47e7d02
@paymentId = 04955f83-684d-4d9e-aff7-65841d170418

### Prepare Payment
POST {{payment}}/preparePayment?amount=1000&rentalReference={{paymentReference}}
Accept: application/json

### Get Payment Status
GET {{payment}}/status/{{paymentId}}
Accept: application/json

### Find paymentID
# Find the payment for a specific payment reference
GET {{payment}}/findPayment?reference={{paymentReference}}
Accept: application/json

### Accept Payment
# Accept a payment
POST {{payment}}/acceptPayment?id={{paymentId}}
Accept: application/json

### Reject Payment
# Reject a payment
POST {{payment}}/rejectPayment?id={{paymentId}}
Accept: application/json

### Get Payment All Status
GET {{payment}}/status
Accept: application/json