:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

= AxonFrameworkのブートストラップ

このステップでは、プロジェクトでAxonFrameworkを使用するための依存関係を設定します。

=== レンタルモジュールでのAxon依存関係の宣言

./rental/build.gradle.kts
[source,kotlin]
--
plugins {
	id("org.springframework.boot") version "3.4.0"
	id("io.spring.dependency-management") version "1.1.6"
}

version = "0.0.1-SNAPSHOT"

java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(21))
	}
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
	implementation("org.axonframework:axon-spring-boot-starter:4.8.1")
	api(project(":core-api"))
}

tasks.named<Test>("test") {
	useJUnitPlatform()
}
--

=== `core-api` モジュールにAxonを使用したメッセージモデリングのサポートを追加

`core-api` モジュールを使用して、レンタルアプリケーションのさまざまなモジュールと通信するメッセージを定義します。そのメッセージの一部には、AxonFrameworkによって提供されるいくつかのJavaアノテーションを使用する必要があります。したがって、プロジェクトにいくつかのAxonFramework依存関係を追加する必要があります。

`core-api` に次の依存関係を追加するだけです：

./core-api/build.gradle.kts
[source,kotlin]
----
plugins {
	id("org.springframework.boot") version "3.4.0"
	id("io.spring.dependency-management") version "1.1.6"
}

version = "0.0.1-SNAPSHOT"

java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(21))
	}
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
	implementation("org.axonframework:axon-modelling:4.8.1")
}

tasks.named<Test>("test") {
	useJUnitPlatform()
}

tasks.withType<JavaCompile>().configureEach {
	options.compilerArgs.add("-parameters")
}
----

これで、自転車レンタルアプリケーションの最初の機能の実装を開始する準備が整いました。