:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

= コマンドハンドラーのテスト

アプリケーションが成長するにつれて、新しい機能を追加するたびに手動で全てをテストすることが難しくなります。アプリケーションが期待通りに動作することを自動的に確認できる方法があると便利です。

すでにアプリケーションのビジネスロジックをチェックするためのユニットテストをいくつか持っているかもしれません。

Axon Framework は、アプリケーション内のコマンド、イベント、およびクエリの処理とハンドリングをテストするための ユニットテストを書ける https://go.axoniq.io/refguide/axon-framework/testing[テストモジュールを提供しています,role=external,window=_blank]。

このチュートリアルでは、`RegisterBikeCommand` を期待通りに処理できるかシステムをテストするユニットテストを実装します。

== Axon Framework テストサポートの設定

プロジェクトの依存関係リストに `axon-test` コンポーネントを追加したので、コマンドハンドラテストを作成できます。

コマンドハンドラのテストを書く前に、ユニットテストをサポートするコンポーネント Axon Framework を追加する必要があります。

これを行うためには、`org.axonframework:axon-test` 依存関係を `rental` モジュールの Gradle ファイルに追加する必要があります。幸いなことに、xref:bootstraping-axonframework.adoc#axon-dependencies[Axon Framework 依存関係を設定した際に既にこの依存関係を追加しました]。

`app/rental/pom.xml` ファイルに `axon-test` モジュールの参照が含まれていることを確認してください:

[,xml]
.rental/pom.xml
----
<dependencies>

    <dependency>
        <groupId>org.axonframework</groupId>
        <artifactId>axon-spring-boot-starter</artifactId>
    </dependency>
    <dependency>
        <groupId>org.axonframework</groupId>
        <artifactId>axon-test</artifactId>
        <scope>test</scope>
    </dependency>
</dependencies>
----

NOTE: Axon Framework が提供するユニットテストのコンポーネントは `test` 実行フェーズ中にのみ必要です。そのため、`axon-test` 依存関係には `testImplementation` を使用します。

== コマンド `BikeTest` の作成

コマンドハンドラのテストを書くために、`rental` モジュールの `/src/test/java/io/axoniq/demo/bikerental/rental/command` に `BikeTest` という名前の新しい Java クラスを作成します。

TIP: また、IDEを使用してユニットテストクラスを作成することもできます。`Bike` クラスを開き、IDEに対応するユニットテストを生成するように指示します。ショートカットやメニューはIDEによって異なる場合がありますが、知っておくと便利なショートカットです。

[,java]
./rental/src/test/java/io/axoniq/demo/bikerental/rental/command/BikeTest.java
----
package io.axoniq.demo.bikerental.rental.command;

public class BikeTest {

}
----

== `AggregateTestFixture` の定義

Axon Framework は、アグリゲートでコマンドをハンドリングする動作をテストすることに特化したユニットテストを作成するコンポーネントを提供します。このコンポーネントは `AggregateTestFixture` と呼ばれます。

NOTE: `AggregateTestFixture` の詳細については、 https://go.axoniq.io/refguide/axon-framework/testing/commands-events#command-model-testing["Command Model Testing" Axon Framework リファレンスガイドのセクションを参照してください,role=external,window=_blank]

`Bike` クラス (テスト対象のコンポーネント) に対する `AggregateTestFixture` 追加及び初期化する必要があります。

[,java]
./rental/src/test/java/io/axoniq/demo/bikerental/rental/command/BikeTest.java
----
package io.axoniq.demo.bikerental.rental.command;

import org.axonframework.test.aggregate.AggregateTestFixture;
import org.junit.jupiter.api.BeforeEach;

public class BikeTest {
    private AggregateTestFixture<Bike> fixture;<.>

    @BeforeEach<.>
    void setUp() {
        fixture = new AggregateTestFixture<>(Bike.class);<.>
    }

}
----
<.> テスト対象 (SUT) となる `Bike` アグリゲートの `AggregateTestFixture` を定義します。
<.> `@BeforeEach` マークされたこのメソッドは、テストクラスのいかなるテストが実行される前に呼び出されることを意味します。このメソッド内に `AggregateTestFixture` の作成コードを追加することで、各テストケースごとに新しいフィクスチャが用意され、異なるテストが独立したものになります。
<.> この行は `Bike` クラス用の新しい `AggregateTestFixture` を作成します。

== コマンドハンドラのテスト

`AggregateTestFixture` を使用すれば、以下の構造でテストを作成できます:

- *Given*: テストの初期状態を設定。Event-Sourcing パターンに従って設計されているシステムでは、コマンドを受け取る前に既に発生したイベントのリストを設定します。
- *When*: 実行したいコマンドを指定。この場合、`RegisterBikeCommand` の処理をテストします。
- *Expect*: コマンド処理後の期待事項を指定。Event-Sourcing システムでは、コマンドハンドラによって生成されるべきイベントの形で这些期を指定します。

システムがバイクの登録要求を正しく処理できるかをチェックするために、ユニットテストにメソッドを定義します:

[,java]
----
package io.axoniq.demo.bikerental.rental.command;

import io.axoniq.demo.bikerental.coreapi.rental.BikeRegisteredEvent;
import io.axoniq.demo.bikerental.coreapi.rental.RegisterBikeCommand;
import org.axonframework.test.aggregate.AggregateTestFixture;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class BikeTest {
    private AggregateTestFixture<Bike> fixture;

    @BeforeEach
    void setUp() {
        fixture = new AggregateTestFixture<>(Bike.class);
    }

    @Test
    void canRegisterBike() {
        fixture.givenNoPriorActivity()<.>
                .when(new RegisterBikeCommand("bikeId-1234", "city-bike", "Amsterdam"))<.>
                .expectEvents(new BikeRegisteredEvent("bikeId-1234", "city-bike", "Amsterdam"));<.>
    }

}
----
<.> この場合、`RegisterBikeCommand` を受け取ったとき、同じ `bikeId` に対して前のイベントが存在しないと予想します。
<.> 送信したい `RegisterBikeCommand` を提供します。
<.> `RegisterBikeCommand` を正常に処理した後、コマンドハンドラが新しいバイクの詳細を持つ `BikeRegisteredEvent` を生成することを期待します。

`AggregateTestFixture` は、アグリゲートを設定してコマンドを実行し (`このステップは、以前のアクティビティがなかったことを指定したため空です`)、`RegisterBikeCommand` のコマンドハンドラーを実行し、指定された値で `BikeRegisteredEvent` が生成されたことをアサートします。

NOTE: フィクスチャを使用してチェックできるさまざまな事項については、Axon Framework リファレンスガイドの https://go.axoniq.io/refguide/axon-framework/testing/commands-events#validation-phase[バリデーションフェーズのセクションを参照してください,role=external,window=_blank]

== テストの実行

IDEから手動でテストを実行することができます。テストが合格することを確認してください。これは、`RegisterBikeCommand` を処理した後、フィクスチャが期待が満たされていることを確認したことを意味します。

手動でテストを実行することに加えて、アプリケーションをビルドするたびにMavenによって自動的に実行されるテストがあります。コマンドラインから `mvn package` を実行すると、テストの実行を見ることができます:

[,console]
----
% mvn package
[...]
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.axoniq.demo.bikerental.rental.command.BikeTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.120 s -- in io.axoniq.demo.bikerental.rental.command.BikeTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[...]
----

このテストの自動実行により、将来的に新しい機能を実装しながらこのコマンド処理の期待される動作を壊すと、すぐにそのことを知ることが保証されます。

その確信を持って、次の機能をシステムに実装して進めることができます。